#cloud-config

coreos:
  etcd:
    # curl -w "\n" https://discovery.etcd.io/new
    discovery: <DISCOVERY_IP>
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
      
  fleet:
    # used for fleetctl ssh command
    public-ip: $private_ipv4
  
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start